CREATE TABLE IF NOT EXISTS Session (
	id INT AUTO_INCREMENT,
	access_token CHAR(64) CHARSET ascii COLLATE ascii_bin NOT NULL,
	refresh_token CHAR(64) CHARSET ascii COLLATE ascii_bin NOT NULL,
	created_date TIMESTAMP NOT NULL,
	user INT NOT NULL,

	PRIMARY KEY(id),
	FOREIGN KEY(user) REFERENCES User(id) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_polish_ci;
