CREATE TABLE IF NOT EXISTS Collection (
	id INT AUTO_INCREMENT,
	name VARCHAR(128) CHARSET utf8 COLLATE utf8_polish_ci NOT NULL,
	description TEXT CHARSET utf8 COLLATE utf8_polish_ci,
	created_date TIMESTAMP NOT NULL,
	modified_date TIMESTAMP NOT NULL,
	owner VARCHAR(254) NOT NULL,

	UNIQUE(name, owner),
	PRIMARY KEY(id),
	FOREIGN KEY(owner) REFERENCES User(username) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_polish_ci;

