CREATE TABLE IF NOT EXISTS Item (
	id INT AUTO_INCREMENT,
	name TINYTEXT CHARSET utf8 COLLATE utf8_polish_ci NOT NULL,
	description TEXTi CHARSET utf8 COLLATE utf8_polish_ci,
	latitude FLOAT,
	longitude FLOAT,
	created_date TIMESTAMP NOT NULL,
	modified_date TIMESTAMP NOT NULL,
	collection INT NOT NULL,
	owner TINYTEXT NOT NULL,

	UNIQUE(name, owner),
	PRIMARY KEY(id),
	FOREIGN KEY(collection) REFERENCES Collection(id) ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY(owner) REFERENCES User(username) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_polish_ci;
