CREATE TABLE IF NOT EXISTS Comment (
id INT AUTO_INCREMENT,
content VARCHAR(160) CHARSET utf8 COLLATE utf8_polish_ci NOT NULL,
created_date TIMESTAMP NOT NULL,
collection INT NOT NULL,
owner INT NOT NULL,

PRIMARY KEY(id),
	FOREIGN KEY(collection) REFERENCES Collection(id) ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY(owner) REFERENCES User(id) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_polish_ci;