CREATE TABLE IF NOT EXISTS Favourite (
	collection INT NOT NULL,
	user INT NOT NULL,

	PRIMARY KEY(collection, user),
	FOREIGN KEY(collection) REFERENCES Collection(id) ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY(user) REFERENCES User(id) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_polish_ci;

